### PR TITLE
Inventory handler app

### PR DESCRIPTION
**Pull request by fuentesloic**
Hey guys,

There is my PR with my interpretation of your rules.

Have a good day and let's go for a talk after :)

CU

### CODE REVIEW

**Comment by fuentesloic** [comment]
@mathieugagne I took a little time to play one more time (according our discussion). That was just for fun but If you have time, could be cool for me to have your review ✌️

**Comment by mathieugagne** [comment]
@Tiush is actually the one who did the review with you. He's off until next week though. Hang on :)

**Comment by TiuSh** [comment]
@fuentesloic That a good step in the right direction, but it'll still need some work to be properly optimized. I couldn't take much time to fully review all your new code, but here's a little help if you want to go further:
- Launch your app in Chrome
- Install the [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) for Chrome, open the debug tools, and in the "React" tab enable the option "Highlight Updates"
2018-10-09 14 54 29_6qw6du
- Once done you should see something like this:
screencast 2018-10-09 at 2 53 51 pm 1
It shows that almost every component is updated on each websocket event. It should help you find a way to optimize your app.

From what I saw there's still some places where you duplicate objects even when it's not needed like [here](https://github.com/fuentesloic/shoe-store/blob/addf751e9adca7560494a6024da8d3c3a93b783e/src/components/Shops/TabContainer.js#L12). 

Good luck ! 😉 🍀

**Comment by fuentesloic** [comment]
@TiuSh thanks a lot, I will close the PR to don't disturb your repo, I will find a way with context to scope the update! thanks a lot for you review :D see ya!

**Pull request closed without merging**
